package com.littlefeet.api.models

/**
* ギターボディータイプ
* Values: sTRATOCASTER,tELECASTER,jAZZMASTER,jAGUAR,mUSTANG,lESPAUL,sEMIACOUSTIC,fULLACOUSTIC,sG,fLYINGV,eXPLORER,fIREBIRD,aCOUSTIC,pRECISIONBASS,jAZZBASE,oTHERGUITAR,oTHERBASE
*/
enum class GuitarBodyType(val value: kotlin.String) {

  STRATOCASTER("STRATOCASTER"),

  TELECASTER("TELECASTER"),

  JAZZMASTER("JAZZ_MASTER"),

  JAGUAR("JAGUAR"),

  MUSTANG("MUSTANG"),

  LESPAUL("LES_PAUL"),

  SEMIACOUSTIC("SEMI_ACOUSTIC"),

  FULLACOUSTIC("FULL_ACOUSTIC"),

  SG("SG"),

  FLYINGV("FLYING_V"),

  EXPLORER("EXPLORER"),

  FIREBIRD("FIRE_BIRD"),

  ACOUSTIC("ACOUSTIC"),

  PRECISIONBASS("PRECISION_BASS"),

  JAZZBASE("JAZZ_BASE"),

  OTHERGUITAR("OTHER_GUITAR"),

  OTHERBASE("OTHER_BASE");

}

