name: Java CI

on:
  pull_request:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: hoge
      uses: duosonic62/github-actions/hoge@master

    - name: huga
      uses: duosonic62/github-actions/huga@master

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build